name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build and run tests
        run: |
          set -euo pipefail
          cd Test
          swift build
          .build/debug/Test
